version: '2'
services:
    znk-app:
        image: znk
        external_links:
            - znk-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/znk?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    znk-mysql:
        extends:
            file: mysql.yml
            service: znk-mysql
